/*
var TL = gsap.timeline();
TL.to("#page1",{
    y:"100vh",
    scale:0.4,
    duration:0,  
})
TL.to("#page1",{
    y:"0vh",
    duration:0.5,
    delay:1,   
})
TL.to("#page1",{
    rotate:"360",
    scale:1,
    duration:0.5,
    delay:1,   
})
*/